---
version: '2'
services:

  zookeeper:
    image: zookeeper:3.6
    container_name: zookeeper
    networks:
      mynet:
    command: "bin/zkServer.sh start-foreground"

  zookeeper2:
    image: zookeeper:3.6
    container_name: zookeeper2
    networks:
      mynet2:
    command: "bin/zkServer.sh start-foreground"
  
  kafka_manager:
    image: deltaprojects/kafka-manager
    container_name: kafka_manager
    ports:
      - 8080:9000
    networks:
      mynet:
      mynet2:
    volumes:
      - hostPath:containerPath:ro
    environment:
      ZK_HOSTS: "zookeeper:2181"
      KAFKA_MANAGER_USERNAME: admin 
      KAFKA_MANAGER_PASSWORD: admin

  kafka1:
    image: bitnami/kafka:3.2.0-debian-11-r3
    networks:
      mynet:
    container_name: kafka1
    environment:
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9091
      KAFKA_LISTENERS: PLAINTEXT://kafka1:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  kafka2:
    image: bitnami/kafka:3.2.0-debian-11-r3
    container_name: kafka2
    networks:
      mynet:
    environment:
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9091
      KAFKA_LISTENERS: PLAINTEXT://kafka2:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  kafka3:
    image: bitnami/kafka:3.2.0-debian-11-r3
    container_name: kafka3
    networks:
      mynet:
    environment:
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9091
      KAFKA_LISTENERS: PLAINTEXT://kafka3:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  kafka11:
    image: bitnami/kafka:3.2.0-debian-11-r3
    networks:
      mynet2:
    container_name: kafka11
    environment:
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper2:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka11:9091
      KAFKA_LISTENERS: PLAINTEXT://kafka11:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  kafka22:
    image: bitnami/kafka:3.2.0-debian-11-r3
    container_name: kafka22
    networks:
      mynet2:
    environment:
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper2:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka22:9091
      KAFKA_LISTENERS: PLAINTEXT://kafka22:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  kafka33:
    image: bitnami/kafka:3.2.0-debian-11-r3
    container_name: kafka33
    networks:
      mynet2:
    environment:
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper2:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka33:9091
      KAFKA_LISTENERS: PLAINTEXT://kafka33:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

networks:
  mynet:
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/24

  mynet2:
    ipam:
      driver: default
      config:
        - subnet: 10.6.0.0/24
